plugins {
    id 'java'
}

group = 'com.platform'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation enforcedPlatform(
            "${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"
    )
    implementation 'io.quarkus:quarkus-rest-jackson'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-hibernate-orm-panache'
    implementation 'io.quarkus:quarkus-hibernate-validator'
    implementation 'io.quarkus:quarkus-smallrye-jwt'
    implementation 'io.quarkus:quarkus-smallrye-jwt-build'
    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    // SQLite for local dev/test
    implementation 'org.xerial:sqlite-jdbc:3.47.1.0'
    implementation 'org.hibernate.orm:hibernate-community-dialects'
    implementation 'io.quarkus:quarkus-flyway'
    implementation 'org.mindrot:jbcrypt:0.4'
    implementation 'software.amazon.awssdk:s3:2.29.52'

    testImplementation 'io.quarkus:quarkus-junit'
    testImplementation 'io.rest-assured:rest-assured'
}

test {
    useJUnitPlatform()
}